theme="solarized_osaka"

[editor]
line-number = "relative"
mouse = false
bufferline = "never"
popup-border = "menu"
auto-pairs = true



[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"



[editor.statusline]
left = ["mode","separator","file-base-name","file-modification-indicator"]
center = ["spinner"]
right = ["diagnostics","spacer","file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"




[editor.file-picker]
hidden = true
ignore = true
git-ignore = true
git-global = true
max-depth = 4



[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
auto-signature-help = true
snippets = true



# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
a = "move_char_left" # Maps the 'a' key to the move_char_left command
w = "move_line_up" # Maps the 'w' key move_line_up
"C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme solarized_osaka"]
e = ":sh hx-wezterm.sh explorer"
[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

